---
- name: Base
  hosts: workstations
  roles:
    - base
    - neovim
    - babashka
  tags: base

- name: Workstation
  hosts: workstations
  become: false
  roles:
    - workstation
  tags: workstation

- name: Inference
  hosts: inference
  roles:
    - base
    - neovim
  tags: inference
