---
- name: Common
  hosts: managed
  roles:
    - base
    - neovim
    - tailscale
    - babashka
  tags: common

- name: Workstation
  hosts: workstations
  become: false
  roles:
    - workstation
  tags: workstation

- name: GNOME Desktop
  hosts: gnome
  become: false
  roles:
    - gnome
  tags: gnome

- name: COSMIC Desktop
  hosts: cosmic
  become: false
  roles:
    - cosmic
  tags: cosmic

- name: Inference
  hosts: inference
  roles:
    - inference
  tags: inference
