---
- name: "Don Dotfiles Host"
  hosts: localhost
  connection: local
  become: true
  vars:
    neovim_nvim_version: v0.9.1
  roles:
    - base
    - neovim
    - babashka
  tags: base

- name: DevOps
  hosts: localhost
  connection: local
  become: false
  roles:
    - devops
    - role: terraform
      become: true
  tags: devops

- name: Workstation
  hosts: localhost
  connection: local
  become: false
  roles:
    - workstation
  tags: workstation
