---
- name: "Don Dotfiles Host"
  hosts: localhost
  connection: local
  become: true
  vars:
    neovim_nvim_version: v0.8.0
  roles:
    - base
    - neovim
  tags: base

- name: DevOps Tooling
  hosts: localhost
  connection: local
  become: true
  roles:
    - terraform
  tags: tooling-devops

