---
# https://docs.ansible.com/ansible/latest/user_guide/collections_using.html

roles:
# Fork of darkwizard242.terraform
  - src: https://github.com/donthorp/ansible-role-terraform.git
    version: debian-install-simplification
    name: terraform

  # Fork of rjsheperd/ansible-role-babashka
  - src: https://github.com/donthorp/ansible-role-babashka.git
    version: personal-main
    name: babashka

  - src: https://github.com/PeterMosmans/ansible-role-customize-gnome.git
    version: master
    name: gnome

