---
- name: Update default paths
  community.general.alternatives:
    name: "{{ item }}"
    path: "{{ lookup('env','HOME') }}/.local/bin/nvim.appimage"
    link: /usr/bin/{{ item }}
    priority: 110
    state: absent
  loop:
  - ex
  - vi
  - view
  - vim
  - vimdiff
  - nvim
  tags: base
