---
- name: Update default paths
  community.general.alternatives:
    name: "{{ item }}"
    path: "/snap/bin/nvim"
    link: /usr/bin/{{ item }}
    priority: 110
  loop:
  - ex
  - vi
  - view
  - vim
  - vimdiff
  - nvim
  tags: base
