---
# tasks file for base

- name: Update APT repository if needed
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install Base Packages
  ansible.builtin.apt: 
    state: latest
    pkg: 
    - ack 
    - ca-certificates 
    - curl
    - dos2unix
    - dirmngr
    - gawk
    - git-extras
    - gnupg
    - inetutils-traceroute
    - jq
    - lsb-release
    - python3-pip
    - ripgrep
    - snapd 
  tags: base

- name: Install Snaps
  community.general.snap:
    name:
      - htop
      - starship
  tags: base

- name: Install Classic Snaps
  community.general.snap:
    name:
      - espanso
    classic: true
  tags: base

- name: Configure Flatpak Repo - Flathub
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

# Font tasks from https://github.com/jahrik/ansible-nvim

- name: Create ~/.local/share/fonts directory
  become: false
  file:
    path: ~/.local/share/fonts
    state: directory
    recurse: true
  tags: base

- name: Download Fira Code Nerd Fonts
  become: false
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/FiraCode.zip 
    dest: ~/.local/share/fonts
    remote_src: yes
    creates: '~/.local/share/fonts/Fira Code Regular Nerd Font Complete.ttf'
  notify: fc-cache
  tags: base
