---
# tasks file for base

#- name: Update APT repository if needed
#  ansible.builtin.apt:
#    update_cache: true
#    upgrade: safe
#    state: latest

- name: Install Base Packages
  ansible.builtin.apt: 
    state: latest
    pkg: 
    - ack 
    - ca-certificates 
    - curl
    - dos2unix
    - dirmngr
    - gawk
    - git-extras
    - gnupg
    - inetutils-traceroute
    - jq
    - lsb-release
    - ripgrep
    - snapd 
  tags: base

- name: Install Snaps
  community.general.snap:
    name:
      - htop
      - starship
  tags: base

- name: Install Classic Snaps
  community.general.snap:
    name:
      - espanso
    classic: true
  tags: base

- name: Configure Flatpak Repo - Flathub
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

