---
# tasks file for base

- name: Install Github CLI GPG Key
  ansible.builtin.get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /etc/apt/keyrings/githubcli-archive-keyring.gpg
    mode: 0644

# TODO: automate retrieval of architecture
#
- name: Add Github CLI APT Repository
  ansible.builtin.apt_repository:
    filename: github-cli
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"

- name: Update APT repository if needed
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install Base Packages
  ansible.builtin.apt: 
    state: latest
    pkg: 
    - ack 
    - autofs
    - ca-certificates 
    - curl
    - dos2unix
    - dirmngr
    - fzf
    - gawk
    - gh
    - git-extras
    - gnupg
    - inetutils-traceroute
    - jq
    - libfuse2
    - lsb-release
    - needrestart
    - nfs-common
    - openssh-server
    - python3-pip
    - ripgrep
    - snapd 
  tags: base

- name: Install Snaps
  community.general.snap:
    name:
      - htop
  tags: base

- name: Install Edge Snaps
  community.general.snap:
    channel: "edge"
    name:
      - starship
  tags: base

- name: Install Classic Snaps
  community.general.snap:
    name:
      - espanso
    classic: true
  tags: base

- name: Configure Flatpak Repo - Flathub
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

# Font tasks from https://github.com/jahrik/ansible-nvim

- name: Create ~/.local/share/fonts directory
  become: false
  file:
    path: ~/.local/share/fonts
    state: directory
    recurse: yes
    mode: 0755
  tags: base

- name: Download Fira Code Nerd Fonts
  become: false
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.zip 
    dest: ~/.local/share/fonts
    remote_src: yes
    creates: '~/.local/share/fonts/FiraCodeNerdFont-Regular.ttf'
  notify: fc-cache
  tags: base
