---
# tasks file for base

- name: Update APT repository if needed
  ansible.builtin.apt:
    update_cache: true
    upgrade: safe
    state: latest

- name: Install Base Packages
  ansible.builtin.apt: 
    state: latest
    pkg: 
    - ack 
    - ca-certificates 
    - curl
    - dos2unix
    - dirmngr
    - gawk
    - git-extras
    - gnupg
    - fonts-firacode
    - jq
    - lsb-release
    - snapd 

- name: Install Snaps
  community.general.snap:
    name:
      - starship
