---
# configuration settings for GNOME/Pop OS
# TODO: fix to detect different environments

- name: Install Python Module - psutil for dconf tasks
  ansible.builtin.pip:
    name: psutil

- name: Configure Terminal to use System Theme
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-colors"
    value: "true"

- name: Configure Terminal to use a Nerd Font
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/font"
    value: "'FiraCode Nerd Font Mono 12'"

- name: Customize Gnome
  include_role:
    name: gnome
  vars:
    gnome_user: "{{ ansible_env.USER }}"
    gnome_gsettings:
      - schema: org.gnome.mutter
        key: center-new-windows
        value: "true"
        state: present

      # Screen Shots
      - schema: org.gnome.shell.keybindings 
        key: screenshot
        value: '"[''<Primary><Shift>Print'', ''<Shift><Alt>dollar'']"'
        state: present
      - schema: org.gnome.shell.keybindings
        key: screenshot-window
        value: '"[''<Primary><Alt>Print'', ''<Shift><Alt>percent'']"'
        state: present
      - schema: org.gnome.shell.keybindings
        key: screenshot
        value: '"[''Print'', ''<Shift><Alt>dollar'']"'
        state: present

      # Desktop
      - schema: org.gnome.desktop.wm.keybindings
        key: activate-window-menu
        value: '"[''<Super>space'']"'
        state: present

