---
# tasks file for workstation

- name: Install GNOME Requirements
  become: true
  ansible.builtin.apt: 
    state: latest
    pkg: 
      - dbus-x11
      - dconf-editor
      - xclip
      - xsel

- name: Include GNOME/DCONF Settings
  include_tasks: ./roles/workstation/tasks/gnome.yml

- name: Install mpg123
  become: true
  ansible.builtin.apt:
    state: latest
    pkg: mpg123

- name: Install Discord
  become: false
  community.general.flatpak: 
    name: com.discordapp.Discord
    method: user
    state: present 

- name: Install Slack 
  become: true
  ansible.builtin.apt: 
    state: latest
    pkg: slack-desktop 

- name: Configure and Install Wavebox
  include_tasks: ./roles/workstation/tasks/wavebox.yml

- name: Configure and Install ULauncher
  include_tasks: ./roles/workstation/tasks/ulauncher.yml

- name: Install Obsidian
  become: false
  community.general.flatpak:
    name: md.obsidian.Obsidian
    method: user
    state: present

- name: DBeaver
  include_tasks: ./roles/workstation/tasks/dbeaver.yml

- name: Install VLC
  become: false
  community.general.flatpak:
    name: org.videolan.VLC
    method: user
    state: present

- name: Install The Gimp
  become: false
  community.general.flatpak:
    name: org.gimp.GIMP
    method: user
    state: present

- name: Install Converseen for Image Conversion
  become: true
  ansible.builtin.apt:
    state: latest
    pkg: converseen

- name: Install PDF Arranger for Simple PDF manipulation
  become: false
  community.general.flatpak:
    name: com.github.jeromerobert.pdfarranger
    method: user
    state: present

- name: Include InsyncHQ
  include_tasks: ./roles/workstation/tasks/insynchq.yml

- name: Install Hugo
  become: true
  community.general.snap:
    name:
      - hugo
    state: present

- name: Install Node.js
  become: true
  community.general.snap:
    name: node
    channel: "16/stable"
    classic: true

- name: Install Parsec
  become: true
  apt:
    deb: https://builds.parsec.app/package/parsec-linux.deb

- name: Install Inkscape
  include_tasks: ./roles/workstation/tasks/inkscape.yml

