---
# tasks file for workstationj

- name: Install GNOME Requirements
  become: true
  ansible.builtin.apt: 
    state: latest
    pkg: 
      - dbus-x11
      - dconf-editor
      - xclip
      - xsel

- name: Include GNOME/DCONF Settings
  include_tasks: ./roles/workstation/tasks/gnome.yml

- name: Install Discord
  become: false
  community.general.flatpak: 
    name: com.discordapp.Discord
    method: user
    state: present 

