---
# tasks file for workstationj

- name: Install Gnome Configuration Tools
  ansible.builtin.apt: 
    state: latest
    pkg: 
      - dconf-editor

- name: Include GNOME/DCONF Settings
  include_tasks: ./roles/workstation/tasks/dconf.yml

- name: Install Discord
  become: false
  community.general.flatpak: 
    name: com.discordapp.Discord
    method: user
    state: present 

