---

- name: Add Ulauncher PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:agornostal/ulauncher
    update_cache: false

- name: Install Ulauncher
  become: true
  ansible.builtin.apt: 
    state: latest
    pkg:
      - ulauncher
