---
# GNOME desktop configuration.
# Runs on hosts in the 'gnome' inventory group only.

- name: Install GNOME requirements
  become: true
  ansible.builtin.apt:
    state: latest
    pkg:
      - dbus-x11
      - dconf-editor
      - xclip
      - xsel
  tags: gnome

- name: Install Python module psutil for dconf tasks
  ansible.builtin.pip:
    name: psutil
  tags: gnome

- name: Configure GNOME Terminal to use system theme colors
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-colors"
    value: "true"
  tags: gnome

- name: Configure GNOME Terminal font to FiraCode Nerd Font
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/font"
    value: "'FiraCode Nerd Font Mono 12'"
  tags: gnome

- name: Center new windows
  community.general.dconf:
    key: /org/gnome/mutter/center-new-windows
    value: "true"
  tags: gnome

- name: Configure screenshot keybinding
  community.general.dconf:
    key: /org/gnome/shell/keybindings/screenshot
    value: "['<Primary><Shift>Print', '<Shift><Alt>dollar']"
  tags: gnome

- name: Configure screenshot-window keybinding
  community.general.dconf:
    key: /org/gnome/shell/keybindings/screenshot-window
    value: "['<Primary><Alt>Print', '<Shift><Alt>percent']"
  tags: gnome

- name: Configure activate-window-menu keybinding
  community.general.dconf:
    key: /org/gnome/desktop/wm/keybindings/activate-window-menu
    value: "['<Super>space']"
  tags: gnome
